# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - simpleapp

# main 브랜치에 push 시 동작하는 워크플로우
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
	  # GitHub에서 제공하는 최신 Ubuntu 실행 환경 사용
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      
    steps:
	    # GitHub 리포지토리에서 소스코드 체크아웃
      - uses: actions/checkout@v4

			# Python 3.12 환경 설정
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      # 가상 환경 생성 및 활성화
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      # 의존성 설치
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # 앱 전체를 압축하여 release.zip 파일 생성
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

			# 다음 단계(deploy)에서 사용할 수 있도록 release.zip을 아티팩트로 업로드
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build # build job이 완료되어야 실행됨
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Azure 로그인에 필요한 권한
      contents: read

    steps:
	    # 이전 build 단계에서 업로드한 release.zip 아티팩트 다운로드
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
			# release.zip 파일 압축 해제
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Azure Web App으로 앱 배포 (Basic authentication - Publish Profile 방식)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'simpleapp'  # 실제 App Service 이름
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip